---
- hosts: spine
  user: root
  roles:
    - common
    - ospf
    - vxsnd
  handlers:
    - include: handlers/main.yml

- hosts: leaf
  user: root
  roles:
    - common
    - ospf
    - vxrd
  handlers:
    - include : handlers/main.yml
